from controller.formatter import JSONFormatter

if __name__ == '__main__':
    a = JSONFormatter('sistema')

    print('\nINSERTIONS\n')
    print(a.formatted_register_address_by_names('sistema', 'rua', 'bairro', 'cidade', 'estado', 'pais'))
    print(a.formatted_register_address_by_names('sistema', 'rua1', 'bairro', 'cidade', 'estado', 'pais'))
    print(a.formatted_register_address_by_names('sistema', 'rua', 'bairro', 'cidade1', 'estado', 'pais'))
    print(a.formatted_register_address_by_names('sistema', 'rua1', 'bairro', 'cidade1', 'estado', 'pais'))
    print(a.formatted_register_condominium('sistema', 'condominio', 23, None, 1))
    print(a.formatted_register_tower('sistema', 't1', 1))
    print(a.formatted_register_tower('sistema', 't2', 1))
    print(a.formatted_register_apartment('sistema', 100, 1))
    print(a.formatted_register_apartment('sistema', 101, 1))
    print(a.formatted_register_apartment('sistema', 100, 2))
    print(a.formatted_register_apartment('sistema', 101, 2))
    print(a.formatted_register_notification('sistema', 1, 'Corredor T1', 'Corredor da torre 1 está interdidato até semana que vem', '2020-02-10', 1))
    print(a.formatted_register_rule('sistema', 'Proibido fumar dentro das torres e apartamentos', 1))
    print(a.formatted_register_guest('sistema', 'joaozinho', '2020-02-03 14:00', 1))
    print(a.formatted_register_service('sistema', 'encanador', 'pedro alberto', '2020-02-03 14:00', 1))
    print(a.formatted_register_service('sistema', 'pizza', None, '2020-02-03 14:00', 2))

    print('\n\n\nSELECTS\n')
    print(a.formatted_get_country_states('sistema', 1))
    print(a.formatted_get_state_cities('sistema', 1))
    print(a.formatted_get_city_addresses('sistema', 1))
    print(a.formatted_get_address_by_id('sistema', 1))
    print(a.formatted_get_condominium_by_id(1))
    print(a.formatted_get_tower_by_id(1))
    print(a.formatted_get_apartment_by_id(1))
    print(a.formatted_get_condominium_employees(1))
    print(a.formatted_get_condominium_rules(1))
    print(a.formatted_get_get_condominium_event_types(1))
    print(a.formatted_get_condominium_towers('sistema', 1))
    print(a.formatted_get_tower_apartments('sistema', 1))
    print(a.formatted_get_apartment_residents('sistema', 1))
    print(a.formatted_get_notification_by_id(1))
    print(a.formatted_get_rule_by_id(1))
    print(a.formatted_get_guest_by_id(1))
    print(a.formatted_get_guests_by_date(1, '2020-02-01', '2020-02-30'))
    print(a.formatted_get_service_by_id(1))
    print(a.formatted_get_service_by_date(1, '2020-02-01', '2020-02-30'))

    print('\n\n\nDELETES\n')
    print(a.formatted_remove_address_by_id('sistema', 1))
    # print(a.formatted_remove_condominium('sistema', 1))
    # print(a.formatted_remove_tower('sistema', 1))
    # print(a.formatted_remove_apartment('sistema', 1))
    # print(a.formatted_remove_notification('sistema', 1))
    # print(a.formatted_remove_rule('sistema', 1))
    # print(a.formatted_remove_guest('sistema', 1))
    # print(a.formatted_remove_service('sistema', 1))

    print('\n\n\nSELECTS\n')
    print(a.formatted_get_address_by_id('sistema', 1))
    print(a.formatted_get_condominium_by_id(1))
    print(a.formatted_get_tower_by_id(1))
    print(a.formatted_get_apartment_by_id(1))
    print(a.formatted_get_condominium_rules(1))
    print(a.formatted_get_get_condominium_event_types(1))
    print(a.formatted_get_condominium_towers('sistema', 1))
    print(a.formatted_get_tower_apartments('sistema', 1))
    print(a.formatted_get_apartment_residents('sistema', 1))
    print(a.formatted_get_notification_by_id(1))
    print(a.formatted_get_rule_by_id(1))
    print(a.formatted_get_guest_by_id(1))
    print(a.formatted_get_guests_by_date(1, '2020-02-01', '2020-02-30'))
    print(a.formatted_get_service_by_id(1))
    print(a.formatted_get_service_by_date(1, '2020-02-01', '2020-02-30'))
